### PR TITLE
Fix changelog tests

### LINKED ISSUE #620: [BUG] Some ChangeLog integration tests are failing
**Describe the bug**
Some of the ChangeLog integration tests are failing

**To Reproduce**
1. Run  `go test -v -tags=integration ./...` in backend directory

### PR DESCRIPTION
**Pull request by kapillamba4**
Fixes #620

### CODE REVIEW

File: backend/app/adapter/db/changelog.go [hunk 1]
```diff
@@ -33,7 +33,7 @@ FROM "%s";`,
 		return []entity.Change{}, err
 	}
 
-	var changeLog []entity.Change
+	changeLog := []entity.Change{}
```
Comment (byliuyang) [inline backend/app/adapter/db/changelog.go:36]: Let's add a comment on why this needed in the code.

Comment (kapillamba4) [reply backend/app/adapter/db/changelog.go:36]: @byliuyang  Should i change expectedChangeLog in testCase to []entity.Change{nil} instead ?
https://stackoverflow.com/questions/29164375/correct-way-to-initialize-empty-slice

Comment (kapillamba4) [reply backend/app/adapter/db/changelog.go:36]: That does'nt work...

Comment (byliuyang) [reply backend/app/adapter/db/changelog.go:37]: Comment should explain why instead of what. Everyone knows `what`. They don't know `why`.

File: backend/app/adapter/db/changelog.go [hunk 2]
```diff
@@ -33,7 +33,8 @@ FROM "%s";`,
 		return []entity.Change{}, err
 	}
 
-	var changeLog []entity.Change
+	// should not initialize as a a nil slice (using var keyword)
```
Comment (byliuyang) [inline backend/app/adapter/db/changelog.go:36]:
```suggestion
	// the consumer of GetChangeLog expects empty slice instead of `nil`
```

File: backend/app/adapter/db/changelog.go (hunk 1 above)
Comment (byliuyang) [reply backend/app/adapter/db/changelog.go:37]: @alldroll Agree!

Comment (kapillamba4) [reply backend/app/adapter/db/changelog.go:37]: the consumer of GetChangeLog expects empty slice instead of `nil` if there are no records

**Comment by byliuyang** [comment]
All comments are addressed. Merging now.
