### PR TITLE
Fix failing integration tests

### LINKED ISSUE #820: [BUG] Some of the integration tests are failing with verbose flag
**Describe the bug**
Some of the backend integration tests are failing on master branch.

**To Reproduce**
1. Run `go test -v -tags=integration ./...` in backend folder.

**Expected behavior**
All integration tests should pass.

**Screenshots**
image
image

### PR DESCRIPTION
**Pull request by kapillamba4**
Fixes #820

### CODE REVIEW

File: backend/app/adapter/sqldb/user_short_link_integration_test.go [hunk 1]
```diff
@@ -117,7 +123,7 @@ func insertUserShortLinkTableRows(
 		_, err := sqlDB.Exec(
 			insertUserShortLinkRowSQL,
 			tableRow.alias,
-			tableRow.userEmail,
+			tableRow.userID,
```
Comment (oatovar) [inline backend/app/adapter/sqldb/user_short_link_integration_test.go:126]: Good catch!

File: backend/app/adapter/sqldb/short_link.go [hunk 2]
```diff
@@ -72,7 +72,7 @@ WHERE "%s"=$5;`,
 		table.ShortLink.ColumnLongLink,
 		table.ShortLink.ColumnExpireAt,
 		table.ShortLink.ColumnUpdatedAt,
-		oldAlias,
+		table.ShortLink.ColumnAlias,
```
Comment (oatovar) [inline backend/app/adapter/sqldb/short_link.go:75]: Another good find 💯

File: backend/app/adapter/sqldb/user_short_link_integration_test.go [hunk 3]
```diff
@@ -57,18 +58,23 @@ func TestListShortLinkSql_FindAliasesByUser(t *testing.T) {
 		{
 			name: "aliases found",
 			userTableRows: []userTableRow{
-				{email: "test@example.com"},
+				{
+					id:    "test",
+					name:  "test user",
```
Comment (arberiii) [inline backend/app/adapter/sqldb/user_short_link_integration_test.go:63]: Shouldn't the name be the same?
```suggestion
					name:  "mockedUser",
```

File: backend/app/adapter/sqldb/userrole.go [hunk 4]
```diff
@@ -30,7 +30,7 @@ WHERE "%s"=$1;
 		table.UserRole.ColumnUserID,
 	)
 
-	var roles []role.Role
+	roles := []role.Role{}
```
Comment (arberiii) [inline backend/app/adapter/sqldb/userrole.go:33]: Why do you prefer this more than var roles []role.Role?

Comment (kapillamba4) [reply backend/app/adapter/sqldb/userrole.go:33]: var initializes roles as a nil slice, this gives problem in assertion

`[]role.Role{} != []role.Role{nil}`

File: backend/app/adapter/sqldb/user_short_link_integration_test.go (hunk 3 above)
Comment (kapillamba4) [reply backend/app/adapter/sqldb/user_short_link_integration_test.go:63]: I agree

Comment (kapillamba4) [reply backend/app/adapter/sqldb/user_short_link_integration_test.go:63]: Will make the changes

File: backend/app/adapter/sqldb/migration/13_create_user_changelog_table.sql [hunk 5]
```diff
@@ -2,7 +2,8 @@
 CREATE TABLE "user_changelog"
 (
     "user_id"              CHARACTER VARYING(5),
-    "email"                CHARACTER VARYING(254) NOT NULL PRIMARY KEY,
+    -- TODO: Add Primary Key Constraint to email on migrate up
```
Comment (oatovar) [inline backend/app/adapter/sqldb/migration/13_create_user_changelog_table.sql:5]: This should be in the standard format of `-- TODO(issue#000)` please make the issue and update this after.

File: backend/app/adapter/sqldb/migration/16_switch_from_email_to_id.sql [hunk 6]
```diff
@@ -28,8 +26,8 @@ ALTER TABLE "user"
...
 
 ALTER TABLE "user_url_relation"
-    ADD COLUMN user_email CHARACTER VARYING(254) NOT NULL;
+    ADD COLUMN user_email CHARACTER VARYING(254);
 ALTER TABLE "user_url_relation"
     ADD CONSTRAINT "user_url_relation_user_email_fkey" FOREIGN KEY (user_email) REFERENCES "user"(email);
-ALTER TABLE "user_url_relation"
-    ADD CONSTRAINT "pk_user_url_relation" PRIMARY KEY (url_alias, user_email);
\ No newline at end of file
+-- TODO: Add Primary Key Constraint to user_email and url_alias on migrate down
```
Comment (oatovar) [inline backend/app/adapter/sqldb/migration/16_switch_from_email_to_id.sql:32]: Link this issue for the primary key todo here as well.

File: backend/app/adapter/sqldb/migration/16_switch_from_email_to_id.sql [hunk 7]
```diff
@@ -28,8 +26,8 @@ ALTER TABLE "user"
...
+-- TODO: Set user_email to NOT NULL on migrate down
```
Comment (oatovar) [inline backend/app/adapter/sqldb/migration/16_switch_from_email_to_id.sql:33]: I think this could also be added to that issue since it is related.

File: backend/app/adapter/sqldb/short_link_integration_test.go [hunk 8]
```diff
@@ -245,7 +245,7 @@ func TestShortLinkSql_CreateShortLink(t *testing.T) {
 
 func TestShortLinkSql_UpdateShortLink(t *testing.T) {
 	createdAt := mustParseTime(t, "2017-05-01T08:02:16-07:00")
-	now := time.Now()
+	now := mustParseTime(t, "2020-05-01T08:02:16-07:00")
```
Comment (oatovar) [inline backend/app/adapter/sqldb/short_link_integration_test.go:248]: 🥇 nice! It's good to have consistent data used when testing.

File: backend/app/adapter/sqldb/short_link_integration_test.go [hunk 9]
```diff
@@ -326,11 +326,14 @@ func TestShortLinkSql_UpdateShortLink(t *testing.T) {
...
 						testCase.newShortLink,
 					)
+					assert.Equal(t, nil, err)
 
+					shortLink, err = shortLinkRepo.GetShortLinkByAlias(testCase.newShortLink.Alias)
 					if testCase.hasErr {
 						assert.NotEqual(t, nil, err)
 						return
 					}
+
```
Comment (oatovar) [inline backend/app/adapter/sqldb/short_link_integration_test.go:336]:
```suggestion
```

File: backend/app/adapter/sqldb/migration/5_create_user_url_relation_table.sql [hunk 10]
```diff
@@ -1,9 +1,10 @@
 -- +migrate Up
 CREATE TABLE user_url_relation
 (
-    user_email CHARACTER VARYING(254) NOT NULL,
+    -- TODO: Add Primary Key Constraint to user_email and url_alias on migrate up
+    -- TODO: Set user_email to NOT NULL on migrate up
```
Comment (oatovar) [inline backend/app/adapter/sqldb/migration/5_create_user_url_relation_table.sql:5]: Update these TODOs as well please 😀

File: backend/app/adapter/sqldb/migration/19_add_constraints_to_user_changelog_table.sql [hunk 11]
```diff
@@ -12,8 +10,7 @@ ALTER TABLE "user_changelog"
 ALTER TABLE "user_changelog"
     DROP CONSTRAINT "user_changelog_pkey";
 ALTER TABLE "user_changelog"
-    ADD COLUMN email CHARACTER VARYING(254) NOT NULL;
-ALTER TABLE "user_changelog"
-    ADD CONSTRAINT "user_changelog_pkey" PRIMARY KEY (email);
+    ADD COLUMN email CHARACTER VARYING(254);
+-- TODO: Add Primary Key Constraint to email on migrate down
```
Comment (oatovar) [inline backend/app/adapter/sqldb/migration/19_add_constraints_to_user_changelog_table.sql:14]: This one should be updated as well

File: backend/app/adapter/sqldb/migration/19_add_constraints_to_user_changelog_table.sql [hunk 12]
```diff
@@ -12,8 +10,7 @@ ALTER TABLE "user_changelog"
 ALTER TABLE "user_changelog"
     DROP CONSTRAINT "user_changelog_pkey";
 ALTER TABLE "user_changelog"
-    ADD COLUMN email CHARACTER VARYING(254) NOT NULL;
-ALTER TABLE "user_changelog"
-    ADD CONSTRAINT "user_changelog_pkey" PRIMARY KEY (email);
```
Comment (oatovar) [inline backend/app/adapter/sqldb/migration/19_add_constraints_to_user_changelog_table.sql:17]: Should the email not be a primary key?

Comment (oatovar) [reply backend/app/adapter/sqldb/migration/19_add_constraints_to_user_changelog_table.sql:17]: I see it's because the user id should be the primary key correct?

File: backend/app/adapter/sqldb/githubsso_integration_test.go [hunk 13]
```diff
@@ -106,6 +153,18 @@ func TestGithubSSOSql_CreateMapping(t *testing.T) {
...
 		{
 			name: "neither SSO user ID nor Short user ID exists",
+			userTableRows: []userTableRow{
+				{
+					id:    "short",
+					email: "short@gmail.com",
+					name:  "short",
+				},
+				{
+					id:    "alpha",
```
Comment (oatovar) [inline backend/app/adapter/sqldb/githubsso_integration_test.go:163]: if these rows are used many times maybe it would be better to have them easier to reuse.
```Go
defaultUserTableRows := []userTableRow{
				{
					id:    "short",
					email: "short@gmail.com",
					name:  "short",
				},
				{
					id:    "alpha",
					email: "alpha@gmail.com",
					name:  "alpha",
				},
			}
```

File: backend/app/adapter/sqldb/migration/19_add_constraints_to_user_changelog_table.sql (hunk 12 above)
Comment (byliuyang) [reply backend/app/adapter/sqldb/migration/19_add_constraints_to_user_changelog_table.sql:17]: @oatovar It would be primary key. We are facing some issues here. @kapillamba4 can explain the details.

Comment (kapillamba4) [reply backend/app/adapter/sqldb/migration/19_add_constraints_to_user_changelog_table.sql:17]: https://github.com/short-d/short/issues/824

Comment (oatovar) [reply backend/app/adapter/sqldb/migration/19_add_constraints_to_user_changelog_table.sql:17]: Thank you for creating the issue @kapillamba4 to track the necessary changes.

File: backend/app/adapter/sqldb/short_link_integration_test.go (hunk 9 above)
Comment (byliuyang) [reply backend/app/adapter/sqldb/short_link_integration_test.go:336]: It's good to have clear logic separation through blank lines.
